name: xeus-cpp
channels:
  - conda-forge
dependencies:
  # Build dependencies
  - make
  - cmake
  # Host dependencies
  - xeus>=5.0.0
  - xeus-zmq>=3.0,<4.0
  - nlohmann_json=3.11.3
  - pugixml
  - cpp-argparse <3.1
  - zlib
  # Test dependencies
  - pytest
  - jupyter_kernel_test>=0.5,<0.6
  - papermill
  - nbformat
  - nbval
  - pytest-rerunfailures
  - doctest